export interface CloudRole {
  id: string;
  number: string;
  title: string;
  category: "INFRASTRUCTURE" | "ARCHITECTURE" | "DEVOPS" | "DATA" | "SECURITY" | "RELIABILITY" | "AI / ML" | "BUSINESS + ARCHITECTURE";
  categoryLabel: string;
  tagline: string;
  responsibilities: string[];
  coreTech: string[];
  techType: "AWS Services" | "Core Technologies";
  accentColor: string;
  badgeBorder: string;
  iconName: string;
  userPassion: string;
}

export const CLOUD_ROLES_DATA: CloudRole[] = [
  {
    id: "cloud-engineer",
    number: "01",
    title: "Cloud Engineer",
    category: "INFRASTRUCTURE",
    categoryLabel: "Infrastructure",
    tagline: "Build, provision, and maintain high-throughput scalable cloud systems and core compute workloads.",
    responsibilities: [
      "Provision and manage scalable cloud infrastructure",
      "Deploy and maintain compute, storage, and networking resources",
      "Configure automated scaling policies and VPC environments",
      "Monitor infrastructure health, alerts, and performance metrics",
      "Implement infrastructure best practices and zero-downtime patching",
    ],
    coreTech: ["EC2", "VPC", "S3", "IAM", "CloudWatch"],
    techType: "AWS Services",
    accentColor: "from-amber-500/20 to-aws-orange/10",
    badgeBorder: "border-amber-500/40 text-amber-400 bg-amber-950/40",
    iconName: "Server",
    userPassion: "I enjoy building infrastructure & provisioning hardware systems in the cloud",
  },
  {
    id: "cloud-architect",
    number: "02",
    title: "Cloud Architect",
    category: "ARCHITECTURE",
    categoryLabel: "Architecture",
    tagline: "Design resilient, distributed multi-tier systems optimized for high availability, security, and performance.",
    responsibilities: [
      "Design scalable, fault-tolerant enterprise cloud architectures",
      "Evaluate trade-offs between AWS compute, storage, and database services",
      "Design for multi-region availability, low latency, and cost efficiency",
      "Create secure multi-tier network topologies and data flow diagrams",
      "Define cloud migration strategies and architecture blueprints",
    ],
    coreTech: ["VPC", "EC2", "S3", "RDS", "CloudFront"],
    techType: "AWS Services",
    accentColor: "from-blue-500/20 to-cyan-500/10",
    badgeBorder: "border-blue-500/40 text-blue-400 bg-blue-950/40",
    iconName: "Layers",
    userPassion: "I enjoy designing high-level distributed systems & blueprinting architectures",
  },
  {
    id: "cloud-devops-engineer",
    number: "03",
    title: "Cloud DevOps Engineer",
    category: "DEVOPS",
    categoryLabel: "Automation + CI/CD",
    tagline: "Unify development and cloud operations with automated deployment pipelines and Infrastructure as Code.",
    responsibilities: [
      "Automate multi-environment cloud infrastructure deployment",
      "Build continuous integration and continuous delivery (CI/CD) pipelines",
      "Manage declarative Infrastructure as Code using Terraform and CDK",
      "Automate integration testing, canary releases, and rollbacks",
      "Improve deployment velocity, developer experience, and release reliability",
    ],
    coreTech: ["Terraform", "GitHub Actions", "AWS CodePipeline", "Docker", "Kubernetes"],
    techType: "Core Technologies",
    accentColor: "from-emerald-500/20 to-teal-500/10",
    badgeBorder: "border-emerald-500/40 text-emerald-400 bg-emerald-950/40",
    iconName: "GitBranch",
    userPassion: "I enjoy automation, CI/CD pipelines, and writing Infrastructure as Code",
  },
  {
    id: "cloud-data-engineer",
    number: "04",
    title: "Cloud Data Engineer",
    category: "DATA",
    categoryLabel: "Data + Pipelines",
    tagline: "Architect petabyte-scale streaming data pipelines, automated ETL workflows, and lakehouses on AWS.",
    responsibilities: [
      "Build scalable batch and real-time streaming data pipelines",
      "Ingest, transform, and partition large multi-source datasets",
      "Design modern cloud data lakehouses and analytical warehouses",
      "Automate serverless ETL extract workflows using AWS Glue",
      "Ensure end-to-end data governance, schema evolution, and query speed",
    ],
    coreTech: ["S3", "Glue", "Athena", "EMR", "Redshift"],
    techType: "AWS Services",
    accentColor: "from-purple-500/20 to-pink-500/10",
    badgeBorder: "border-purple-500/40 text-purple-400 bg-purple-950/40",
    iconName: "Database",
    userPassion: "I enjoy working with data, ETL pipelines, and massive analytical warehouses",
  },
  {
    id: "cloud-security-engineer",
    number: "05",
    title: "Cloud Security Engineer",
    category: "SECURITY",
    categoryLabel: "Security",
    tagline: "Fortify cloud boundaries with zero-trust identity policies, encryption at rest/transit, and automated threat response.",
    responsibilities: [
      "Secure cloud infrastructure across networking, compute, and data tiers",
      "Implement fine-grained zero-trust IAM policies and key management",
      "Monitor continuous security threats and detect anomalous behaviors",
      "Configure web application firewalls (WAF) and automated guardrails",
      "Perform vulnerability scans, penetration audits, and compliance checks",
    ],
    coreTech: ["IAM", "KMS", "WAF", "GuardDuty", "Security Hub"],
    techType: "AWS Services",
    accentColor: "from-rose-500/20 to-red-500/10",
    badgeBorder: "border-rose-500/40 text-rose-400 bg-rose-950/40",
    iconName: "ShieldCheck",
    userPassion: "I enjoy cybersecurity, zero-trust policies, and defending cloud perimeters",
  },
  {
    id: "cloud-sre",
    number: "06",
    title: "Cloud SRE (Site Reliability)",
    category: "RELIABILITY",
    categoryLabel: "Reliability",
    tagline: "Apply software engineering principles to maintain five-nines uptime, telemetry, and chaos engineering.",
    responsibilities: [
      "Maintain 99.999% uptime and high availability across production clusters",
      "Monitor live system telemetry, metrics, distributed traces, and logs",
      "Define and track critical SLIs, SLOs, and error budget thresholds",
      "Automate operational self-healing mechanisms and incident response",
      "Perform post-mortems and proactive chaos engineering drills",
    ],
    coreTech: ["CloudWatch", "Kubernetes", "Terraform", "Prometheus", "Grafana"],
    techType: "Core Technologies",
    accentColor: "from-cyan-500/20 to-blue-500/10",
    badgeBorder: "border-cyan-500/40 text-cyan-400 bg-cyan-950/40",
    iconName: "Activity",
    userPassion: "I enjoy reliability, uptime engineering, and production monitoring",
  },
  {
    id: "cloud-ml-engineer",
    number: "07",
    title: "Cloud ML Engineer",
    category: "AI / ML",
    categoryLabel: "AI / ML",
    tagline: "Deploy foundation models, build distributed training clusters, and scale generative AI endpoints.",
    responsibilities: [
      "Build, train, and deploy production machine learning pipelines",
      "Deploy scalable foundation models with Amazon Bedrock and SageMaker",
      "Implement Retrieval-Augmented Generation (RAG) with vector databases",
      "Monitor inference latency, GPU resource utilization, and model drift",
      "Integrate AI microservices seamlessly into modern web applications",
    ],
    coreTech: ["SageMaker", "Bedrock", "S3", "Lambda", "ECR"],
    techType: "AWS Services",
    accentColor: "from-amber-400/20 to-yellow-500/10",
    badgeBorder: "border-yellow-500/40 text-yellow-400 bg-yellow-950/40",
    iconName: "Bot",
    userPassion: "I enjoy AI, machine learning models, and building Generative AI apps",
  },
  {
    id: "cloud-solutions-architect",
    number: "08",
    title: "Cloud Solutions Architect",
    category: "BUSINESS + ARCHITECTURE",
    categoryLabel: "Business + Architecture",
    tagline: "Bridge corporate business requirements with state-of-the-art AWS architectures and ROI optimization.",
    responsibilities: [
      "Translate business objectives into robust, cost-optimized cloud solutions",
      "Apply the AWS Well-Architected Framework across 6 core pillars",
      "Collaborate with executive stakeholders, developers, and product leads",
      "Recommend right-sized cloud services, licensing models, and SLAs",
      "Guide enterprise digital transformation and cloud modernization roadmaps",
    ],
    coreTech: ["AWS Well-Architected", "EC2", "S3", "RDS", "Lambda"],
    techType: "AWS Services",
    accentColor: "from-indigo-500/20 to-violet-500/10",
    badgeBorder: "border-indigo-500/40 text-indigo-400 bg-indigo-950/40",
    iconName: "Boxes",
    userPassion: "I enjoy technology + business strategy and solving client problem statements",
  },
];
